import {mulberry32,hashSeed,int} from './rng.js';
import {createCharacter,alignment,manifest} from './character.js';
import {drawCard,applyEffect} from './cards.js';
import {createMap} from './map.js';
const $=id=>document.getElementById(id);let seed=0,rng,character,map,pending=null;
const show=id=>{['titleScreen','seedScreen','birthScreen','gameShell','deathScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id))};
function log(text,accent=''){const el=document.createElement('div');el.className='log-entry';el.innerHTML=`<time>TURN ${String(character.turn).padStart(2,'0')} / AGE ${String(character.age).padStart(2,'0')}</time>${accent?`<strong>${accent}</strong> `:''}${text}`;$('log').prepend(el)}
function phaseName(){return character.age<13?'CHILDHOOD':character.age<19?'ACADEMY':'WORLD MAP'}
function update(){if(!character)return;const c=character,p=phaseName();$('charName').textContent=c.name;$('healthText').textContent=`${Math.max(0,c.health)} / ${c.maxHealth}`;$('healthBar').style.width=Math.max(0,c.health/c.maxHealth*100)+'%';[['strengthText','strengthBar','strength'],['intText','intBar','intelligence'],['willText','willBar','willpower']].forEach(([t,b,k])=>{$(t).textContent=c[k];$(b).style.width=Math.min(100,c[k]*2)+'%'});$('moralityText').textContent=(c.morality>0?'+':'')+c.morality;$('moralMarker').style.left=(c.morality+100)/2+'%';$('alignText').textContent=alignment(c);$('powerTier').textContent=c.powerTier?`POWER TIER ${c.powerTier}`:'POWER DORMANT';$('traitList').innerHTML=c.traits.length?c.traits.map(t=>`<span class="trait">${t}</span>`).join(''):'<span class="muted">Your story is still forming.</span>';$('ageText').textContent=`AGE ${String(c.age).padStart(2,'0')}`;$('phaseChip').innerHTML=`${p} <b>${p==='CHILDHOOD'?'AGE 5–12':p==='ACADEMY'?'AGE 14–18':'ADULTHOOD'}</b>`;$('kicker').textContent=`CHAPTER ${p==='CHILDHOOD'?'01':p==='ACADEMY'?'02':'03'} / ${c.powerTier?'THE AWAKENED':'BEFORE THE SPARK'}`;$('chapterTitle').textContent=p==='CHILDHOOD'?'Small Moments, Big Consequences':p==='ACADEMY'?'Learn What You Are':'The City Is Your Board';$('turnText').textContent=`TURN ${String(c.turn).padStart(2,'0')}`;$('wealthText').textContent='$'+c.wealth;$('fateText').textContent=c.fate>=0?'+'+c.fate:c.fate;$('diceLabel').textContent=(c.age<12?'D4 · 1–4 STEPS':c.age<18?'D6 · 1–6 STEPS':'D8 · 1–8 STEPS');drawBoard();save();}
function save(){if(!character)return;localStorage.setItem('awakening-save',JSON.stringify({version:2,seed,character,map}))}
function drawBoard(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0c171d';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#152d35';ctx.lineWidth=1;for(let x=0;x<w;x+=38){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=38){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const pts=map.map((n,i)=>({x:n.x+40,y:n.y}));ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='#315b64';ctx.lineWidth=3;ctx.stroke();pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,i===character.location?15:9,0,Math.PI*2);ctx.fillStyle=i===character.location?'#52e0e6':i>3?'#ff704755':'#1a3a43';ctx.fill();ctx.strokeStyle=i===character.location?'#bafafa':'#47737b';ctx.stroke();ctx.fillStyle='#a8bdc1';ctx.font='11px Space Mono';ctx.fillText(map[i].name,p.x-35,p.y+30)});$('locationText').textContent=map[character.location]?.name||'UNKNOWN'}
function birth(){seed=hashSeed($('startSeed').value||String(Math.floor(Math.random()*999999)));rng=mulberry32(seed);character=createCharacter(seed);map=createMap(seed);$('hashedSeed').textContent=`HASHED TIMELINE: ${seed>>>0}`;$('birthName').textContent=character.name;$('birthBlurb').textContent=`Born into a world of ordinary rules. The dice suggest otherwise. Wealth: $${character.wealth}.`;const vals=[['VITALITY',character.health],['STRENGTH',character.strength],['INTELLIGENCE',character.intelligence],['WILLPOWER',character.willpower]];$('birthStats').innerHTML=vals.map(v=>`<div><b>${v[1]}</b><span>${v[0]}</span></div>`).join('');show('birthScreen')}
function begin(){show('gameShell');$('log').innerHTML='';log('A new life begins. The variables are in motion.','SYSTEM');update()}
function openEvent(card,roll){pending=card;$('eventType').textContent=`EVENT // ${String(character.turn).padStart(2,'0')}`;$('eventFate').textContent=`FATE ${roll.fate>=0?'+':''}${roll.fate}`;$('eventArt').textContent=card.art;$('eventKicker').textContent=card.kicker;$('eventTitle').textContent=card.title;$('eventText').textContent=card.text;$('choices').innerHTML=card.choices.map((c,i)=>`<button class="choice" data-i="${i}"><span>${c.label}</span><small>${c.tag}</small></button>`).join('');$('outcome').classList.add('hidden');$('continueBtn').classList.add('hidden');$('eventModal').classList.remove('hidden');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(+b.dataset.i))}
function choose(i){const choice=pending.choices[i],effects=choice.effect(character);applyEffect(character,effects);if(effects.potential)character.traits.push(choice.tag.replace('+ ','').replaceAll(' ','_'));if(character.age>=12&&!character.powerTier){manifest(character,seed);character.traits.push(character.powerTier==='F'?'INDOMITABLE':'AWAKENED');log(`Manifestation event. Power tier ${character.powerTier}.`,'THE SPARK')}$('choices').classList.add('hidden');$('outcome').textContent=choice.result;$('outcome').classList.remove('hidden');$('continueBtn').classList.remove('hidden');update();if(character.health<=0)setTimeout(()=>die('A life cut short by the weight of its own choices.'),500)}
function die(reason){character.health=0;$('eventModal').classList.add('hidden');$('deathTitle').textContent=character.name.toUpperCase()+' // THE END';$('deathText').textContent=reason;$('deathSeed').textContent=seed>>>0;$('deathStats').innerHTML=`<div><b>${character.age}</b><span>AGE</span></div><div><b>${character.powerTier||'F'}</b><span>POWER</span></div><div><b>${character.morality}</b><span>MORALITY</span></div><div><b>${character.turn}</b><span>TURNS</span></div>`;localStorage.removeItem('awakening-save');show('deathScreen')}
$('titleNew').onclick=()=>show('seedScreen');$('titleContinue').onclick=()=>{const s=JSON.parse(localStorage.getItem('awakening-save')||'null');if(!s)return toast('NO SAVED LIFE FOUND');seed=s.seed;character=s.character;map=s.map||createMap(seed);rng=mulberry32(seed);begin()};$('randomStart').onclick=()=>{$('startSeed').value=Math.random().toString(36).slice(2,10);$('startSeed').dispatchEvent(new Event('input'))};$('startSeed').oninput=()=>{$('hashedSeed').textContent=$('startSeed').value?`HASHED TIMELINE: ${hashSeed($('startSeed').value)>>>0}`:''};$('beginLife').onclick=birth;$('acceptBirth').onclick=begin;$('rerollBirth').onclick=birth;$('newLifeDeath').onclick=()=>show('seedScreen');$('sameSeed').onclick=()=>{$('startSeed').value=String(seed>>>0);birth()};$('continueBtn').onclick=()=>{$('eventModal').classList.add('hidden');$('choices').classList.remove('hidden');$('rollBtn').disabled=false;$('turnSummary').textContent='The next moment is yours to shape.'};$('rollBtn').onclick=()=>{const sides=character.age<12?4:character.age<18?6:8,steps=int(rng,1,sides);character.fate=steps===1?-1:steps===sides?1:0;character.turn++;character.location=(character.location+steps)%map.length;if(character.turn%2===0)character.age++;$('rollBtn').disabled=true;$('turnSummary').textContent=`Moved ${steps} space${steps>1?'s':''}. A moment finds you.`;log(`Moved to ${map[character.location].name}.`,'MOVE');openEvent(drawCard(character),{fate:character.fate});update()};$('newSeed').onclick=()=>{$('seedInput').value=Math.floor(Math.random()*999999);location.reload()};$('resetBtn').onclick=()=>show('seedScreen');$('saveBtn').onclick=()=>{save();toast('RUN SAVED TO THIS DEVICE')};function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}const canvas=$('board'),ctx=canvas.getContext('2d');$('continueHint').textContent=localStorage.getItem('awakening-save')?'SAVE FOUND':'NO SAVE';show('titleScreen');window.addEventListener('resize',()=>character&&drawBoard());
